POST http://localhost:3333/sessions HTTP/1.1
content-type: application/json

{
    "email": "alexsandro.g.bezerra@gmail.com",
    "password": "123456"
}

### 

GET http://localhost:3333/tasks HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzI0Mzg3ODYsImV4cCI6MTYzMjQzOTY4Niwic3ViIjoiMSJ9.6cp0D7-1Cn-4IfbdRtsqPoctPBTsWSkacZWPPJ-0TlQ
